version: "3.9"

services:
  database:
    image: postgres:14
    container_name: database_uber_eats
    restart: always
    ports: 
      - ${DB_PORT}:5432
    environment: 
      - POSTGRES_USER= ${DB_USERNAME}
      - POSTGRES_PASSWORD= ${DB_PASSWORD}
      - POSTGRES_DB= ${DB_NAME}
      
  app:
    build: .
    container_name: uber_eats_server
    restart: always
    ports:
      - 3333:3333
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database

volumes: 
  pgdata: 
    driver: local