version: "3.9"

services:
  database:
    image: postgres:14
    container_name: database_uber_eats
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=uber_eats
      
  app:
    build: .
    container_name: uber-eats-server
    restart: always
    ports:
      - 3333:3333
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database

volumes: 
  pgdata: 
    driver: local